# Generated by Django 5.1.1 on 2024-10-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_open', models.IntegerField(default=0)),
                ('incident_assigned', models.IntegerField(default=0)),
                ('incident_in_progress', models.IntegerField(default=0)),
                ('incident_pending', models.IntegerField(default=0)),
                ('incident_resolved', models.IntegerField(default=0)),
                ('incident_closed', models.IntegerField(default=0)),
                ('service_pending', models.IntegerField(default=0)),
                ('service_approved', models.IntegerField(default=0)),
                ('service_rejected', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
