# Generated by Django 5.1.1 on 2024-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_servicerequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/'),
        ),
    ]
