# Generated by Django 5.1.1 on 2024-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_remove_serviceitem_pic_servicerequest_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
