# Generated by Django 5.1.1 on 2024-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='ticket_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
