# Generated by Django 5.1.1 on 2024-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0002_alter_incidentreport_ticket_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='incident_report.status'),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='incident_report.incidentreport')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident_report.status')),
            ],
        ),
    ]
