# Generated by Django 5.1.1 on 2024-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0003_status_remove_incidentreport_assigned_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuschange',
            name='status',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='incident_report',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='StatusChange',
        ),
    ]
