# Generated by Django 5.1.1 on 2024-11-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_report', '0005_status_remove_incidentreport_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='incident_report.status'),
        ),
    ]
