# Generated by Django 5.1.1 on 2024-11-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('incident_report', '0007_alter_incidentreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
